"""add movies data to media table part1 try1

Revision ID: 15d9f8c23473
Revises: 1ea7ffa0721e
Create Date: 2025-09-15 18:56:48.117960

"""
import csv
from datetime import date
from pathlib import Path
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15d9f8c23473'
down_revision: Union[str, Sequence[str], None] = '1ea7ffa0721e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

BATCH_SIZE = 1000
CSV_PATH = Path(__file__).parent.parent / "data" / "movies_data_part1.csv"


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
