"""add movies data to media table

Revision ID: 1ea7ffa0721e
Revises: 61f00556be4b
Create Date: 2025-09-14 18:15:56.073273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ea7ffa0721e'
down_revision: Union[str, Sequence[str], None] = '61f00556be4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass

        # conn.execute(media_table.insert(), items)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
