"""add  description column media table

Revision ID: 2744e5c3b00d
Revises: d76f45952a57
Create Date: 2025-09-14 17:57:10.422432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2744e5c3b00d'
down_revision: Union[str, Sequence[str], None] = 'd76f45952a57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('description', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media', 'description')
    # ### end Alembic commands ###
