"""alter columns names forum_post table

Revision ID: 4db305dafd18
Revises: b40ae56df90c
Create Date: 2025-09-13 12:45:39.890368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4db305dafd18'
down_revision: Union[str, Sequence[str], None] = 'b40ae56df90c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('forum_post', "ds_title", new_column_name="title")
    op.alter_column('forum_post', "ds_content", new_column_name="content")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('forum_post', "title", new_column_name="ds_title")
    op.alter_column('forum_post', "content", new_column_name="ds_content")
    # ### end Alembic commands ###
