"""create media table

Revision ID: 75b8da44d98a
Revises: 9f977d889751
Create Date: 2025-09-14 16:45:24.989376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75b8da44d98a'
down_revision: Union[str, Sequence[str], None] = '9f977d889751'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_imdb', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('original_title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('dt_launch', sa.Date(), nullable=False),
    sa.Column('original_language', sa.String(), nullable=False),
    sa.Column('midia_type', sa.String(), nullable=False),
    sa.Column('poster_url', sa.String(), nullable=True),
    sa.Column('popularity', sa.Float(), nullable=True),
    sa.Column('vote_average', sa.Float(), nullable=True),
    sa.Column('vote_count', sa.Integer(), nullable=True),
    sa.Column('adult', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_original_title'), 'media', ['original_title'], unique=False)
    op.create_index(op.f('ix_media_title'), 'media', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_media_title'), table_name='media')
    op.drop_index(op.f('ix_media_original_title'), table_name='media')
    op.drop_table('media')
    # ### end Alembic commands ###
