"""create table forum participant

Revision ID: 775a348a5ad6
Revises: eabfe94c8478
Create Date: 2025-09-20 21:05:45.907612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '775a348a5ad6'
down_revision: Union[str, Sequence[str], None] = 'eabfe94c8478'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forum_participant',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('forum_group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['forum_group_id'], ['forum_group.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'forum_group_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('forum_participant')
    # ### end Alembic commands ###
