"""added name and profile picture user

Revision ID: 78ff1fc34fa8
Revises: 33d55ad92bce
Create Date: 2025-10-04 14:04:31.389287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78ff1fc34fa8'
down_revision: Union[str, Sequence[str], None] = '33d55ad92bce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.String(), nullable=False))
    op.add_column('user', sa.Column('profile_picture', sa.String(), nullable=False))
    op.create_index(op.f('ix_user_name'), 'user', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_name'), table_name='user')
    op.drop_column('user', 'profile_picture')
    op.drop_column('user', 'name')
    # ### end Alembic commands ###
