"""add data to genre table

Revision ID: 82494958485e
Revises: da306334fe3c
Create Date: 2025-09-14 00:33:40.293163

"""
import csv
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pathlib import Path


# revision identifiers, used by Alembic.
revision: str = '82494958485e'
down_revision: Union[str, Sequence[str], None] = 'da306334fe3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


CSV_PATH = Path(__file__).parent.parent / "data" / "genres.csv"

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()

    genre_table = sa.table(
        "genre",
        sa.column("id", sa.Integer),
        sa.column("name", sa.String),
    )

    genres = []
    with open(CSV_PATH, newline="", encoding="utf-8") as csvfile:
        reader = csv.DictReader(csvfile)
        for row in reader:
            genres.append({"id": int(row["id"]), "name": row["name"]})

    if genres:
        conn.execute(genre_table.insert(), genres)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    conn.execute("DELETE FROM genre")
    # ### end Alembic commands ###
