"""create table genre

Revision ID: 914bd3dba645
Revises: 88c99ab63700
Create Date: 2025-09-14 00:24:45.371957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '914bd3dba645'
down_revision: Union[str, Sequence[str], None] = '88c99ab63700'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    pass


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
