"""update columns media table id imdb

Revision ID: d427dea0fcf5
Revises: e6fc362dbbad
Create Date: 2025-09-14 17:54:02.215891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd427dea0fcf5'
down_revision: Union[str, Sequence[str], None] = 'e6fc362dbbad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.Inspector.from_engine(conn)

    columns = [c['name'] for c in inspector.get_columns('media')]

    if 'id_imdb' not in columns:
        op.add_column('media', sa.Column('id_imdb', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media', 'id_imdb')
    # ### end Alembic commands ###
