"""delete description column media table

Revision ID: d76f45952a57
Revises: d427dea0fcf5
Create Date: 2025-09-14 17:56:30.695460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd76f45952a57'
down_revision: Union[str, Sequence[str], None] = 'd427dea0fcf5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('description', sa.VARCHAR(), nullable=False))
    # ### end Alembic commands ###
