"""delete media table

Revision ID: da72ac820cff
Revises: acf7d91c020c
Create Date: 2025-09-14 18:03:05.828909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da72ac820cff'
down_revision: Union[str, Sequence[str], None] = 'acf7d91c020c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_media_original_title'), table_name='media')
    op.drop_index(op.f('ix_media_title'), table_name='media')
    op.drop_table('media')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('original_title', sa.VARCHAR(), nullable=False),
    sa.Column('dt_launch', sa.DATE(), nullable=False),
    sa.Column('original_language', sa.VARCHAR(), nullable=False),
    sa.Column('poster_url', sa.VARCHAR(), nullable=True),
    sa.Column('popularity', sa.FLOAT(), nullable=True),
    sa.Column('vote_average', sa.FLOAT(), nullable=True),
    sa.Column('vote_count', sa.INTEGER(), nullable=True),
    sa.Column('adult', sa.BOOLEAN(), nullable=False),
    sa.Column('media_type', sa.VARCHAR(), nullable=False),
    sa.Column('id_imdb', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_title'), 'media', ['title'], unique=False)
    op.create_index(op.f('ix_media_original_title'), 'media', ['original_title'], unique=False)
    # ### end Alembic commands ###
