"""column profile picture nullable

Revision ID: e174be98bd88
Revises: 78ff1fc34fa8
Create Date: 2025-10-04 14:10:08.964814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e174be98bd88'
down_revision: Union[str, Sequence[str], None] = '78ff1fc34fa8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'profile_picture',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'profile_picture',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
