"""columnavatar created

Revision ID: f8ba21d65cb6
Revises: e174be98bd88
Create Date: 2025-10-11 01:11:07.875399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8ba21d65cb6'
down_revision: Union[str, Sequence[str], None] = 'e174be98bd88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('avatar', sa.Integer(), nullable=False))
    op.drop_column('user', 'profile_picture')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('profile_picture', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('user', 'avatar')
    # ### end Alembic commands ###
